### ISSUE TITLE
Detailed roxygen review

### ISSUE THREAD

**Issue by mitchellmanware** [kyle-messier/amadeus#29]
Thorough review and updating of roxygen2 documentation. Explore hiding auxiliary functions with "@keywords internal"

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
To include more useful descriptions of functions such as MODIS bands. process_modis_sds has codes , but should include land-surface temperature, NDVI, etc. as secondary descriptors.

**Comment by mitchellmanware** [comment]
https://github.com/kyle-messier/amadeus/pull/36
